### PR TITLE
Add licenses for the pom generation.

### PR DESCRIPTION
**Pull request by slide**
Added the ability to specify a license that will be in the generated pom.

### CODE REVIEW

**Comment by slide** [comment]
This is in preparation for a gradle plugin for checking plugin hosting requirements. A license is one of the things that we request for hosting.

**Comment by slide** [comment]
Initial code for the hosting checker is here: https://github.com/slide/gradle-hosting-checker-plugin

@batmat take a look if you are interested

**Comment by batmat** [comment]
\o/ very cool @slide ! LGTM, though I'm really not gradle-fluent at all. 

Seems like @daspilker is the current maintainer or main committer? cc @abayer ?

Thanks!

**Comment by daspilker** [comment]
Cool thanks, it just needed some tweaks (https://github.com/jenkinsci/gradle-jpi-plugin/commit/7c723c48d17b312fcf45cf10f2d66b07929f8445).

**Comment by slide** [comment]
Thanks for the tweaks and the merge!

**Comment by slide** [comment]
Just out of curiosity, do you know when the next release including these changes will be?

**Comment by daspilker** [comment]
Released as 0.21.0 just now. Btw, what's your plan with the hosting checker plugin? Would it make sense to integrate it into the JPI plugin? Why does it need to be a separate plugin?

**Comment by slide** [comment]
It's possible that hosting requirements will evolve more quickly than the JPI plugin would need to be released, so I made it a separate plugin for that reason. Thanks for the release.

**Comment by daspilker** [comment]
We can do quick JPI plugin releases. Or how about publishing the rules as a library and let the JPI plugin depend on the [latest version](http://stackoverflow.com/a/10373813/1271460)? Having the rules as a build-tool-neutral library is probably a good idea anyway if you want to use the same rules from the Maven plugin as well.

**Comment by slide** [comment]
@daspilker All good points. @batmat what do you think about a common rule library?

**Comment by batmat** [comment]
+1, I like the idea!

2016-12-02 18:48 GMT+01:00 Alex Earl <notifications@github.com>:

**Pull request merged**
