### PR TITLE
Make the plugin compatible with Gradle 3.4

### PR DESCRIPTION
**Pull request by wolfs**
Currently, the plugin breaks when using/compiling it with Gradle 3.4: https://scans.gradle.com/s/vyrbuts35dotw

This is mostly due to using the internal `SoftwareComponentInternal`. This PR exposes the problems. I am not sure if I will have time addressing the problems.

### CODE REVIEW

**Comment by wolfs** [comment]
I fixed the compile errors but now there are many test failures: https://scans.gradle.com/s/hnuyxk33itx4s

**Comment by wolfs** [comment]
I obviously did the wrong thing when fixing the compile errors. I would need to provide a `UsageContext` instead of a usage for the component. This still would not solve the use of the internal API.

**Comment by wolfs** [comment]
Thanks @daspilker!

**Comment by daspilker** [comment]
@wolfs I tried another approach and removed the usage of internal API as suggested [here](https://github.com/gradle/gradle/issues/1361#issuecomment-281438429). See https://github.com/jenkinsci/gradle-jpi-plugin/pull/85.

I tested it with Job DSL and it seems to work. Can you test if that works for you?

It comes at the cost of doing more POM customization magic because the `UsageContext` of `WebApplication` does not declare any dependencies, see [WebApplication.java#L57](https://github.com/gradle/gradle/blob/v3.4.0/subprojects/plugins/src/main/java/org/gradle/api/internal/java/WebApplication.java#L57).

**Comment by bmuschko** [comment]
@daspilker Looks like you went ahead and changed the code based on [my suggestions](https://github.com/gradle/gradle/issues/1361#issuecomment-281438429). I read the [page on the Jenkins plugin structure](https://wiki.jenkins-ci.org/display/JENKINS/Plugin+Structure) and it sounds to me as if the JPI artifact is rather a representation of a JAR.

> A plugin is really just a jar file that follows a certain set of conventions

In turn you might want to think about not applying the `War` plugin and going with just the Java plugin. That might further reduce the noise in the plugin code.

**Comment by daspilker** [comment]
@bmuschko thanks for looking into this. I picked the War task because the plugin archive needs to have the classes in `WEB-INF/classes` and it's libraries in `WEB-INF/libraries`. And I also need to publish a plain Jar containing the classes only, preferably from the same project. So I would need to reconfigure the "main" Jar task to assemble the plugin directory structure and publish the plugin as the main component. Then I would need add a second Jar task to assemble the "plain" Jar and publish that as additional artifact. Would that be feasible and better?

**Comment by bmuschko** [comment]
@daspilker I think it would work either way. It's probably just a matter of how you want the JPI to be represented. It's OK as is if you think about the archive as a WAR file. For end users of the plugin it probably won't matter too much. The only difference they'd see is `jar` vs. `war`.

**Comment by wolfs** [comment]
Fixed by #85 instead.

**Pull request closed without merging**
