### PR TITLE
[JENKINS-25007] Update to Gradle 2.3, publish JAR

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by daspilker** [comment]
@wolfs can you please review this PR? Is the packaging configuration as it is supposed to be? The PR is based on Gradle 2.3-rc-1, so it needs to be updated when 2.3 has been released. I tested it with the Job DSL plugin and it works as expected.

**Comment by wolfs** [comment]
Looks good to me. I also tried it out with the job-dsl-plugin.

**Comment by daspilker** [comment]
Still works with 2.3-rc-3.

**Comment by daspilker** [comment]
And updated to 2.3-rc-4...

**Pull request merged**
