### PR TITLE
avoid internal API

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by wolfs** [comment]
@daspilker I tried this PR with the [Gradle](https://github.com/jenkinsci/gradle-plugin/) plugin, and the resulting pom is missing some exclusions.
This is contained in the pom when publishing with the old plugin:
```xml
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>structs</artifactId>
      <version>1.3</version>
      <exclusions>
        <exclusion>
          <artifactId>*</artifactId>
          <groupId>*</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```
while this is contained when publishing with this PR:
```xml
   <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>structs</artifactId>
      <version>1.3</version>
    </dependency>
```

**Comment by wolfs** [comment]
The manifest for the `hpi` file looks good.

**Comment by wolfs** [comment]
Regarding the pom - it could be that the "new" pom is actually better. It is just different to what we had before.

**Comment by daspilker** [comment]
@wolfs yes, the new POM is better. There is code that should remove these * exclusions, but it seems to be broken. https://github.com/jenkinsci/gradle-jpi-plugin/blob/0.21.0/src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizer.groovy#L88-L91

**Comment by daspilker** [comment]
@wolfs ah, I added that code in 0.20.0 and the Gradle plugin is at 0.18.1, so it's not broken. https://github.com/jenkinsci/gradle-jpi-plugin/compare/0.19.0...0.20.0

**Comment by wolfs** [comment]
\o/ Time to upgrade!

**Pull request merged**
