### PR TITLE
[JENKINS-45126] fixed incremental build

### PR DESCRIPTION
**Pull request by daspilker**

### CODE REVIEW

**Comment by daspilker** [comment]
@wolfs please take a look

Only setting the manifest attributes at execution time did not fix the problem. The reproducer was flaky, failing ~50%. I also had to set the manifest attributes as input properties to really fix the problem. Is that expected?

**Comment by daspilker** [comment]
Hm, the reproducer is still flaky.

**Comment by wolfs** [comment]
It is not expected. Which test is failing? Can you reproduce the failure locally?

**Comment by wolfs** [comment]
By the way, if you capture the test results as part of the pipeline build instead of failing the build it would be much easier to debug. I switched the [gradle-plugin build](https://github.com/jenkinsci/gradle-plugin/blob/master/Jenkinsfile) to use `buildPlugin()` only in its `Jenkinsfile`. I think you can configure the target platforms with this, too, so you may want to replace your `Jenkinsfile` with this.

**Comment by daspilker** [comment]
@wolfs you can reproduce the issue by resetting this branch to https://github.com/jenkinsci/gradle-jpi-plugin/pull/89/commits/a43906fddf75cb0e034613d0bf8634554dac6939. I can reproduce this locally, but only ~50% of my builds fail:

    org.jenkinsci.gradle.plugins.jpi.JpiManifestSpec > JPI is built if manifest changed FAILED
        org.spockframework.runtime.SpockComparisonFailure at JpiManifestSpec.groovy:187

There is a similar test `JAR is built if manifest changed` which tests the generated JAR instead of the JPI. That test never failed locally. But it failed in one of the 4 CI configurations even with my workaround from https://github.com/jenkinsci/gradle-jpi-plugin/pull/89/commits/c1a643b9b0c101908f13993b0343169ad35ce547. I would assume that there should be no big difference between the `War` task building the JPI and the `Jar` task building the JAR?!?

I can not switch the `Jenkinsfile` to `buildPlugin()` because that's specific for Jenkins plugins, e.g. archiving HPI/JPI files. I used `buildPlugin()` as a starting point for the `Jenkinsfile`. I will try to add `try/catch` block to capture the test results.

**Comment by wolfs** [comment]
@daspilker Finally I remembered that I added [ignoreFailures=true](https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/build.gradle#L113) when running on CI to not make the build fail but capture test results instead.

**Comment by daspilker** [comment]
@wolfs I found that in your build script and added the change to `master` an hour ago: https://github.com/jenkinsci/gradle-jpi-plugin/commit/ae8ed1aafd580fc350a10dcdd1c33a1bfd99b213.

**Comment by wolfs** [comment]
@daspilker I had a closer look why `org.jenkinsci.gradle.plugins.jpi.JpiManifestSpec.JPI is built if manifest changed` was failing. I saw that updating Gradle to 3.4 makes the test pass while using Gradle 3.3 or 3.2.1 made the test fail consistently for me. It seems to be something we fixed in Gradle, but I can't remember what could have been this.
Could you require Gradle 3.4 for using the plugin (or at least update the wrapper for the plugin itself to 3.4)?

**Comment by wolfs** [comment]
@daspilker Ping?

**Comment by daspilker** [comment]
@wolfs I update master to Gradle 3.5.1 and rebased this branch to master. I can not reproduce the problem locally and CI is green. But the manifest attributes have to be set as input properties. Otherwise the reproducer fails. Shall I merge the branch as it is?

**Comment by wolfs** [comment]
I was under the impression that the reproducer would pass on Gradle 3.5.1 without adding the inputs explicitly. I will try tonight and see what I can find.

**Comment by wolfs** [comment]
@daspilker I tried a few times locally: https://scans.gradle.com/s/hj2tywsl65x54/tests
The test passes. I am using on b8438e8a9c62de89cdeabb4d94cce05af3d75a7c, i.e. without adding the inputs explicitely. Do you have some logs (of the test) or a build scan when the test is failing?

**Comment by wolfs** [comment]
OTOH, it is more important to have a working incremental build than to have a little bit nicer build script.
If the test still fails for you on https://github.com/jenkinsci/gradle-jpi-plugin/commit/b8438e8a9c62de89cdeabb4d94cce05af3d75a7c, then just merge this PR to fix the problem. We can still open a new issue for investigating why the attributes are not tracked by default.

**Comment by daspilker** [comment]
@wolfs here is a scan of a failed build: https://scans.gradle.com/s/62wdj6jhbfldq Or do I need to scan the build run by the failing test?

**Comment by wolfs** [comment]
@daspilker Thanks to the build scan I can now see that you have been running the test on Windows. Could you try to modify the test as shown [here](https://github.com/jenkinsci/gradle-jpi-plugin/pull/93/files#diff-ec9eac413ea38a241fbd841fb3fea09bR184) to see if it helps?

**Pull request merged**
