### PR TITLE
Fixed transitive plugin dependency resolution

### PR DESCRIPTION
**Pull request by wolfs**
This PR fixes JENKINS-45412 by using the suggestion from https://github.com/jenkinsci/gradle-jpi-plugin/pull/87#issuecomment-334796399.

### CODE REVIEW

**Comment by daspilker** [comment]
I tried this with job-dsl-plugin (https://github.com/daspilker/job-dsl-plugin/tree/gradle-3.5), but got compile errors:

    :job-dsl-plugin:compileGroovy
    warning: [options] bootstrap class path not set in conjunction with -source 1.7
    C:\Users\Daniel\Projects\job-dsl-plugin\job-dsl-plugin\src\main\groovy\javaposse\jobdsl\plugin\ExecuteDslScripts.java:46: error: package org.jenkinsci.plugins.configfiles does not exist
    import org.jenkinsci.plugins.configfiles.GlobalConfigFiles;
                                            ^
I then tried to analyze the dependencies but got this error:

    Execution failed for task ':job-dsl-plugin:dependencies'.
    > Failed to notify dependency resolution listener.
       > Cannot change dependencies of configuration ':job-dsl-plugin:providedCompile' after it has been included in dependency resolution. Use 'defaultDependencies' instead of 'beforeResolve' to specify default dependencies for a configuration.
       > Cannot change dependencies of configuration ':job-dsl-plugin:providedCompile' after it has been included in dependency resolution. Use 'defaultDependencies' instead of 'beforeResolve' to specify default dependencies for a configuration.

**Comment by daniel-beck** [comment]
> This PR fixes JENKINS-45412

https://issues.jenkins-ci.org/browse/JENKINS-45412 ?

**Comment by daniel-beck** [comment]
Not a Gradle JPI Plugin user, but may it not be better to force people to be explicit about their dependencies?

**Comment by daspilker** [comment]
@wolfs I did some debugging. When `:compileJava` is running, the `beforeResolve` action is only called for `compileClasspath`, but not for the super configurations. Is that intended? I pushed https://github.com/jenkinsci/gradle-jpi-plugin/pull/87/commits/a0590876d503071bbdb1997122ea14becf34ff85 along with your commit to #87 to react on the resolution of `compileClasspath`. Now it's working for job-dsl-plugin. But it seems a bit random to use the resolution of `compileClasspath` as a hook. Listing dependencies still does not work.

**Comment by daspilker** [comment]
Is now part of #87.

**Comment by daspilker** [comment]
@daniel-beck 

> Not a Gradle JPI Plugin user, but may it not be better to force people to be explicit about their dependencies?

Many users requested this. The HPI Maven plugin also does transitive plugin dependency resolution. And with plugin dependency lists getting larger (Pipeline, SCM, Branch API, etc.) it's a real pain to find the transitive closure. I even saw a script for Script Console that creates a Gradle dependency list from the installed plugins.

**Comment by daniel-beck** [comment]
@daspilker 

> The HPI Maven plugin also does transitive plugin dependency resolution.

Right, and that caused https://issues.jenkins-ci.org/browse/JENKINS-44200?focusedCommentId=316043&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-316043 because it apparently wasn't clear to plugin developers what's optional, and what's not.

Consider the following:

> Your plugin, A, depends on plugin B 1.0. B 1.0 has a dependency on C. A uses C functionality without declaring a C dependency. What happens when B 2.0 drops the dependency on C, and you update it in your running instance? I haven't tried it, but I'm pretty sure it's **broken Jenkins**.

Jenkins doesn't know the transitive dependencies of plugin versions it doesn't even have installed, so cannot prevent this problem IIUC, resulting in the same stability problems as we've worked for years (https://jenkins.io/changelog/#v2.16, https://jenkins.io/changelog/#v2.12, https://jenkins.io/changelog/#v2.4, etc.) to prevent.

This change is a liability. TBH I'd require plugin dependencies at least be explicit even in Maven HPI Plugin (CC @jglick @stephenc can we opt into something like this?).

---

> it's a real pain to find the transitive closure

Note that nobody should ever depend e.g. on `pipeline-aggregator`. Frequent review finding by Jesse or Stephen. If this change is meant to enable that use case, I urge you to reconsider. It can't be that difficult to figure out what APIs you're actually accessing. Sure, you'll likely end up with a dozen or so dependencies, but if your plugin is doing that much, that seems reasonable.

**Comment by wolfs** [comment]
@daniel-beck I agree that pulling in transitive plugin dependencies may pose a problem. On the other hand, requiring transitive `jar` dependencies seems to be convenient. Still, this also might be a problem. Mainly because there is no way in a maven `pom.xml` to declare that a library is required for a consumer of the artifact as opposed to being required for compilation of the producer of the artifact. Gradle aims to solve this for Java libraries by the new `java-library` plugin and the `api` and `implementation` configurations. See for example the [Gradle userguide](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation) or this [blog post](https://blog.gradle.org/incremental-compiler-avoidance). 
Now we are at the decision whether to pull in transitive dependencies for plugins or not. https://github.com/jenkinsci/gradle-plugin/pull/35#r74808249 seems to suggest that it is a good idea to pull in at least transitive `jar` dependencies. I am not quite sure what the `maven-hpi-plugin` is doing exactly. All in all it would be good to have little differences in behaviour between the `gradle-jpi-plugin` and the `maven-hpi-plugin`.

**Comment by daniel-beck** [comment]
FWIW I filed the current behavior of maven-hpi-plugin as a bug ([JENKINS-47564](https://issues.jenkins-ci.org/browse/JENKINS-47564)), with explanation why it's a terrible idea, destabilizing Jenkins.

**Pull request closed without merging**
